{% set version = "2.5.7" %}

package:
  name: pyscaffold
  version: {{ version }}

source:
  fn: PyScaffold-{{ version }}.tar.gz
  url: https://github.com/blue-yonder/pyscaffold/archive/v{{ version }}.tar.gz
  sha256: 7c404ec6f724d9658eed3aa7150d0829f1f477e367209a07735e8e1dcdb3b3a3

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 0
  preserve_egg_dir: True
  entry_points:
    - putup=pyscaffold.cli:run

requirements:
  build:
    - python
    - setuptools
    - pyscaffold
    - six
  run:
    - python
    - six

test:
  imports:
    - pyscaffold
    - pyscaffold.templates
  commands:
    - putup --help

about:
  home: http://pyscaffold.readthedocs.org/
  license: BSD 3-Clause
  summary: 'Template tool for putting up the scaffold of a Python project.'

extra:
  recipe-maintainers:
    - ocefpaf
