{% set name = "pyscaffold" %}
{% set version = "4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyScaffold-{{ version }}.tar.gz
  sha256: d849f9a2e15bdcf165e19f96835f0b17e1a2d59d4c561c445b827a081de6d262

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - putup = pyscaffold.cli:run


requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm >=5
  run:
    - python >=3.6
    - platformdirs >=2,<4
    - configupdater >=3.0,<4
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - tomlkit >=0.7.0,<2
    - packaging >=20.7
    - importlib-metadata
    - colorama >=0.4.4

test:
  imports:
    - pyscaffold
    - pyscaffold.templates
  commands:
    - putup --help
    - pytest -m "not slow and not system" --cov-config setup.cfg -k "not test_issue506 and not test_iterate_entry_points"
    # - pip check # pytest-shutil has a path.py bug and we cannot run this here.
  source_files:
    - tests
    - setup.cfg
  requires:
    - git
    - pip
    - setuptools
    - tomlkit
    - certifi
    - tox
    - python-build
    - pre-commit
    - sphinx
    - flake8
    - virtualenv
    - pytest
    - pytest-cov
    - pytest-shutil
    - pytest-virtualenv
    - pytest-fixture-config
    - pytest-xdist
    - twine

about:
  home: https://pyscaffold.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Template tool for putting up the scaffold of a Python project
  dev_url: https://github.com/pyscaffold/pyscaffold/

extra:
  recipe-maintainers:
    - ocefpaf
    - maresb
    - FlorianWilhelm
    - abravalheri
